version: "3.9"

services:
    server:
        container_name: papprika-prakticum-server
        image: papprika-prakticum-server
        build:
            context: .
            dockerfile: packages/server/Dockerfile.prod
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
          - postgres
        environment:
          SERVER_PORT: ${SERVER_PORT}

    postgres:
      container_name: papprika-postgres
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

