version: "3.9"

services:
  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: packages/server/Dockerfile.dev
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "24678:24678"
    environment:
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/packages/client/node_modules
      - /app/packages/server/node_modules

  postgres:
    image: postgres:14     
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

